# Generated by Django 3.2.24 on 2024-02-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240227_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, help_text='ingredients present in the product', max_length=500, null=True, verbose_name='ingredients'),
        ),
    ]
