# Generated by Django 3.2.24 on 2024-02-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='size_unit',
            field=models.CharField(default='gm', max_length=2),
        ),
    ]
