# Generated by Django 3.2.24 on 2024-02-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sku_size_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='size_unit',
        ),
    ]
