# Generated by Django 3.2.24 on 2024-02-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_sku_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size'),
        ),
    ]
