# Generated by Django 3.2.24 on 2024-02-28 09:32

from django.db import migrations


class Migration(migrations.Migration):


    def transfer_price_to_selling_price(apps, schema_editor):
        Product = apps.get_model('products', 'Product')
        Sku = apps.get_model('products', 'Sku')
        for product in Product.objects.all():
            sku, created = Sku.objects.get_or_create(product=product, size=0, defaults={'selling_price': 0.0, 'platform_commission': 0, 'cost_price': 0})
            sku.selling_price = product.price
            sku.save()


    dependencies = [
        ('products', '0009_auto_20240228_1457'),
    ]

    operations = [
        migrations.RunPython(transfer_price_to_selling_price)
    ]




