# Generated by Django 3.2.24 on 2024-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20240228_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
