# Generated by Django 3.2.24 on 2024-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_sku_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
