# Generated by Django 3.2.24 on 2024-02-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_sku_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
