# Generated by Django 3.2.24 on 2024-02-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_sku_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sku',
            name='unique_product_size',
        ),
        migrations.AddField(
            model_name='sku',
            name='measurement_unit',
            field=models.CharField(choices=[('gm', 'Grams'), ('kg', 'Kilograms'), ('mL', 'Milliliters'), ('L', 'Liters'), ('pc', 'Piece')], default='gm', max_length=2),
        ),
        migrations.AddField(
            model_name='sku',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending for approval'), (1, 'Approved'), (2, 'Discontinued')], default=0),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.CheckConstraint(check=models.Q(('size__lte', 999)), name='size_limit'),
        ),
    ]
